In [1]:
import pandas as pd
import numpy as np
# getting the data from the txt file and convert it intothe python...!
records=pd.read_csv(r"C:\Users\suman\OneDrive\Documents\Python Documents\bigmarket.txt", sep='\t')
records

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [4]:
#copied the data to a variable that can help to edit the duplicate data...!
test=records.copy()
test

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [ ]:
# to know thw description of the data..!
test.describe()

In [7]:
# to get the information of the data
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Month   25 non-null     object
 1   Store   25 non-null     object
 2   Sales   25 non-null     int64
dtypes: int64(1), object(2)
memory usage: 732.0+ bytes

In [12]:
#to get the Missing values count
test.isnull().sum()
#if missing values is present fill the values with 0
test.fillna(0)
#to drop the Missing Values for temporary
test.dropna()

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [5]:
test.shape

(25, 3)

In [6]:
test.columns

Index(['Month', 'Store', 'Sales'], dtype='object')

In [16]:
test=test['Sales'].astype('float')

In [17]:
test.dtype

dtype('float64')

In [8]:
test=test['Sales'].astype('object')

In [10]:
records

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [11]:
test1=records.copy()
test1

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [103]:
test1=test1.rename(columns={'Store':'Branch'})

In [104]:
test1.columns

Index(['Month', 'Branch', 'Sales', 'Profit'], dtype='object')

In [106]:
test1=test1.assign(ProfitorLoss=np.where(test1['Sales']>35000,'Profit','Loss'))
test1.drop('Profit', axis=1,inplace=True)

In [107]:
#Which Month getting profits list...!
print('The Total Profits Count is: ',(test1['ProfitorLoss']=='Profit').sum())
test1.loc[test1['ProfitorLoss'] == 'Profit',['Month','Branch','Sales','ProfitorLoss']]

The Total Profits Count is:  9

    Month Branch  Sales ProfitorLoss
9     Feb      E  46267       Profit
12  March      C  47814       Profit
13  March      D  36069       Profit
16    Apr      B  40241       Profit
17    Apr      C  47488       Profit
21    May      B  40001       Profit
22    May      C  46482       Profit
23    May      D  46313       Profit
24    May      E  47594       Profit

In [39]:
##Which Month getting Losses list...!
print('The Total Profits Count is: ',(test1['ProfitorLoss']=='Loss').sum())
test1.loc[test1['ProfitorLoss'] == 'Loss',['Month','Branch','Sales','ProfitorLoss']]

The Total Profits Count is:  16

    Month Branch  Sales ProfitorLoss
0     Jan      A  31037         Loss
1     Jan      B  20722         Loss
2     Jan      C  24557         Loss
3     Jan      D  34649         Loss
4     Jan      E  29795         Loss
5     Feb      A  29133         Loss
6     Feb      B  22695         Loss
7     Feb      C  28312         Loss
8     Feb      D  31454         Loss
10  March      A  32961         Loss
11  March      B  26451         Loss
14  March      E  31874         Loss
15    Apr      A  27253         Loss
18    Apr      D  25432         Loss
19    Apr      E  33880         Loss
20    May      A  29487         Loss

In [41]:
#the Data of jan & Apr Month 
test1[test1['Month'].isin(['Jan','Apr'])]

   Month Branch  Sales ProfitorLoss
0    Jan      A  31037         Loss
1    Jan      B  20722         Loss
2    Jan      C  24557         Loss
3    Jan      D  34649         Loss
4    Jan      E  29795         Loss
15   Apr      A  27253         Loss
16   Apr      B  40241       Profit
17   Apr      C  47488       Profit
18   Apr      D  25432         Loss
19   Apr      E  33880         Loss

In [42]:
test1[(test1['Month'].isin(['Jan','Apr','May']))& (test1['ProfitorLoss'] == 'Profit')]

   Month Branch  Sales ProfitorLoss
16   Apr      B  40241       Profit
17   Apr      C  47488       Profit
21   May      B  40001       Profit
22   May      C  46482       Profit
23   May      D  46313       Profit
24   May      E  47594       Profit

In [44]:
test1[(test1['Month'].isin(['Jan','Apr','May']))|(test1['ProfitorLoss'] == 'Profit')]

    Month Branch  Sales ProfitorLoss
0     Jan      A  31037         Loss
1     Jan      B  20722         Loss
2     Jan      C  24557         Loss
3     Jan      D  34649         Loss
4     Jan      E  29795         Loss
9     Feb      E  46267       Profit
12  March      C  47814       Profit
13  March      D  36069       Profit
15    Apr      A  27253         Loss
16    Apr      B  40241       Profit
17    Apr      C  47488       Profit
18    Apr      D  25432         Loss
19    Apr      E  33880         Loss
20    May      A  29487         Loss
21    May      B  40001       Profit
22    May      C  46482       Profit
23    May      D  46313       Profit
24    May      E  47594       Profit

In [108]:
print((test1['Branch']=='A').sum())
test1[~(test1['Branch']=='A')]

5

    Month Branch  Sales ProfitorLoss
1     Jan      B  20722         Loss
2     Jan      C  24557         Loss
3     Jan      D  34649         Loss
4     Jan      E  29795         Loss
6     Feb      B  22695         Loss
7     Feb      C  28312         Loss
8     Feb      D  31454         Loss
9     Feb      E  46267       Profit
11  March      B  26451         Loss
12  March      C  47814       Profit
13  March      D  36069       Profit
14  March      E  31874         Loss
16    Apr      B  40241       Profit
17    Apr      C  47488       Profit
18    Apr      D  25432         Loss
19    Apr      E  33880         Loss
21    May      B  40001       Profit
22    May      C  46482       Profit
23    May      D  46313       Profit
24    May      E  47594       Profit

In [53]:
test1.query("Month in ['Jan','Feb'] and ProfitorLoss == 'Profit'")

  Month Branch  Sales ProfitorLoss
9   Feb      E  46267       Profit

In [56]:
test1.query("Branch in ['A','C','D','E'] and Sales > 30000 and ProfitorLoss == 'Profit'")

    Month Branch  Sales ProfitorLoss
9     Feb      E  46267       Profit
12  March      C  47814       Profit
13  March      D  36069       Profit
17    Apr      C  47488       Profit
22    May      C  46482       Profit
23    May      D  46313       Profit
24    May      E  47594       Profit

In [109]:
#Assigning the profit or Loss percentage ...!
test1= test1.assign(Profit=((test1['Sales']*0.10)/test1['Sales'])*100)
test1

    Month Branch  Sales ProfitorLoss  Profit
0     Jan      A  31037         Loss    10.0
1     Jan      B  20722         Loss    10.0
2     Jan      C  24557         Loss    10.0
3     Jan      D  34649         Loss    10.0
4     Jan      E  29795         Loss    10.0
5     Feb      A  29133         Loss    10.0
6     Feb      B  22695         Loss    10.0
7     Feb      C  28312         Loss    10.0
8     Feb      D  31454         Loss    10.0
9     Feb      E  46267       Profit    10.0
10  March      A  32961         Loss    10.0
11  March      B  26451         Loss    10.0
12  March      C  47814       Profit    10.0
13  March      D  36069       Profit    10.0
14  March      E  31874         Loss    10.0
15    Apr      A  27253         Loss    10.0
16    Apr      B  40241       Profit    10.0
17    Apr      C  47488       Profit    10.0
18    Apr      D  25432         Loss    10.0
19    Apr      E  33880         Loss    10.0
20    May      A  29487         Loss    10.0
21    May      B  40001       Profit    10.0
22    May      C  46482       Profit    10.0
23    May      D  46313       Profit    10.0
24    May      E  47594       Profit    10.0

In [70]:
test1.head()

  Month Branch  Sales ProfitorLoss  Profit
0   Jan      A  31037         Loss    10.0
1   Jan      B  20722         Loss    10.0
2   Jan      C  24557         Loss    10.0
3   Jan      D  34649         Loss    10.0
4   Jan      E  29795         Loss    10.0

In [72]:
test1.tail()

   Month Branch  Sales ProfitorLoss  Profit
20   May      A  29487         Loss    10.0
21   May      B  40001       Profit    10.0
22   May      C  46482       Profit    10.0
23   May      D  46313       Profit    10.0
24   May      E  47594       Profit    10.0

In [73]:
test1.sample(15)

    Month Branch  Sales ProfitorLoss  Profit
24    May      E  47594       Profit    10.0
0     Jan      A  31037         Loss    10.0
5     Feb      A  29133         Loss    10.0
18    Apr      D  25432         Loss    10.0
15    Apr      A  27253         Loss    10.0
4     Jan      E  29795         Loss    10.0
16    Apr      B  40241       Profit    10.0
3     Jan      D  34649         Loss    10.0
22    May      C  46482       Profit    10.0
1     Jan      B  20722         Loss    10.0
14  March      E  31874         Loss    10.0
21    May      B  40001       Profit    10.0
10  March      A  32961         Loss    10.0
20    May      A  29487         Loss    10.0
2     Jan      C  24557         Loss    10.0

In [121]:
#Creating the New Rows with User Input's
a=input('Enter the Month:')
b=input('Enter the Branch:')
c=int(input('Enter the Sale:'))
new_data = {
    'Month': a,
    'Branch': b,
    'Sales': c ,
    'ProfitorLoss': np.where(c>35000,'Profit','Loss'),
    'Profit': ((c*0.10)/c)*100
}
new_row=pd.DataFrame([new_data])
test=pd.concat([test,new_row], ignore_index=True)
test.tail()

Enter the Month: Sep
Enter the Branch: S
Enter the Sale: 15421

   Month Branch  Sales ProfitorLoss  Profit
22   May      C  46482       Profit    10.0
23   May      D  46313       Profit    10.0
24   May      E  47594       Profit    10.0
25   May      F  53821       Profit    10.0
26   Sep      S  15421         Loss    10.0

In [123]:
test['Month'].sort_values()

    Month Branch  Sales ProfitorLoss  Profit
0     Jan      A  31037         Loss    10.0
1     Jan      B  20722         Loss    10.0
2     Jan      C  24557         Loss    10.0
3     Jan      D  34649         Loss    10.0
4     Jan      E  29795         Loss    10.0
5     Feb      A  29133         Loss    10.0
6     Feb      B  22695         Loss    10.0
7     Feb      C  28312         Loss    10.0
8     Feb      D  31454         Loss    10.0
9     Feb      E  46267       Profit    10.0
10  March      A  32961         Loss    10.0
11  March      B  26451         Loss    10.0
12  March      C  47814       Profit    10.0
13  March      D  36069       Profit    10.0
14  March      E  31874         Loss    10.0
15    Apr      A  27253         Loss    10.0
16    Apr      B  40241       Profit    10.0
17    Apr      C  47488       Profit    10.0
18    Apr      D  25432         Loss    10.0
19    Apr      E  33880         Loss    10.0
20    May      A  29487         Loss    10.0
21    May      B  40001       Profit    10.0
22    May      C  46482       Profit    10.0
23    May      D  46313       Profit    10.0
24    May      E  47594       Profit    10.0
25    May      F  53821       Profit    10.0
26    Sep      S  15421         Loss    10.0

In [122]:
test.dtypes

Month            object
Branch           object
Sales             int64
ProfitorLoss     object
Profit          float64
dtype: object

In [4]:
test3=records.copy()
pd.pivot_table(test3, index=['Month'], values=['Sales'], aggfunc='mean')

         Sales
Month
Apr    34858.8
Feb    31572.2
Jan    28152.0
March  35033.8
May    41975.4

In [5]:
data={"Name":["Dima","James","Mia","Emity","Roben","John","Jordan"], "Salary":[50000,45000,51000,60000,41000,21450,34000], 

      "Gender":["F","M","F","F","M","M","M"], "Age":[23,34,36,29,28,25,30]}

 

df_emp=pd.DataFrame(data)

df_emp

     Name  Salary Gender  Age
0    Dima   50000      F   23
1   James   45000      M   34
2     Mia   51000      F   36
3   Emity   60000      F   29
4   Roben   41000      M   28
5    John   21450      M   25
6  Jordan   34000      M   30

In [6]:
df_melt=df_emp.melt(id_vars=['Gender'],value_vars=['Age'])
df_melt

  Gender variable  value
0      F      Age     23
1      M      Age     34
2      F      Age     36
3      F      Age     29
4      M      Age     28
5      M      Age     25
6      M      Age     30