In [17]:
import pandas as pd
import numpy as np
records=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\customer.xlsx", sheet_name=0)
records2=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\customer.xlsx", sheet_name=1)
#customer=pd.concat(records.values(), ignore_index=True)
print(records)
print(records2)

   Order_ID  Cust_ID  Order
0       222      101    789
1       223      102    465
2       224      103    674
3       225      104    564

In [13]:
insurance=pd.read_csv(r"C:\Users\suman\OneDrive\Documents\Python Documents\insurance_data_with_day.csv")
insurance.head(6)

,patientid,dayofmonth,age,gender,bmi,bloodpressure,diabetic,children,smoker,region,claim
0,1,19,39.0,male,23.2,91,Yes,0,No,southeast,1121.87
1,2,8,24.0,male,30.1,87,No,0,No,southeast,1131.51
2,3,11,27.0,male,33.3,82,Yes,0,No,southeast,1135.94
3,4,5,NaN,male,33.7,80,No,0,No,northwest,1136.40
4,5,21,30.0,male,34.1,100,No,0,No,northwest,1137.01
5,6,16,47.0,male,34.4,96,Yes,0,No,northwest,1137.47

In [14]:
ecommerce=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\Ecommerce_data.xlsx", sheet_name='Cust_data')
ecommerce

   Cust_ID  Age  Gender     City
0   Cust_1   35    Male   Mumbai
1   Cust_2   24  Female  Chennai
2   Cust_3   20  Female    Delhi
3   Cust_4   45    Male  Chennai
4   Cust_5   37    Male   Mumbai
5   Cust_6   40  Female   Mumbai
6  Cust_10   50    Male     Pune

In [15]:
ecommerce2=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\Ecommerce_data.xlsx", sheet_name='Ord_data')
ecommerce2

   Ord_ID  Cust_ID  Ord_quantity      Sales Ord_priority
0  Ord_10   Cust_1           4.0  3237.0000       Medium
1  Ord_14   Cust_2           NaN        NaN          NaN
2  Ord_25   Cust_3           2.0   422.7000          Low
3  Ord_29   Cust_4          15.0  4571.7900         High
4  Ord_34   Cust_5           8.0  4233.1500          Low
5  Ord_52   Cust_6           3.0   164.0200         High
6  Ord_71  Cust_11           1.0   147.6400          Low
7  Ord_94   Cust_8           7.0  3410.1575       Medium

In [19]:
sales_transaction=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\sales_transactions.xlsx", sheet_name=0)
sales_transaction1=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\sales_transactions.xlsx", sheet_name=1)
print(sales_transaction)
print(sales_transaction1)

   account           name  order       sku  quantity  unit price  ext price
0   383080       Will LLC  10001  B1-20000         7       33.69     235.83
1   383080       Will LLC  10001  B1-86481         3       35.99     107.97
2   412290  Jerde-Hilpert  10005  S1-06532        48       55.82    2679.36
3   412290  Jerde-Hilpert  10005  S1-47412        44       78.91    3472.04
4   412290  Jerde-Hilpert  10005  S1-27722        36       25.42     915.12
5   218895      Kulas Inc  10006  S1-27722        32       95.66    3061.12
6   218895      Kulas Inc  10006  B1-33087        23       22.55     518.65
7   218895      Kulas Inc  10006  B1-20000        -1       72.18     -72.18
   account      name  order       sku  quantity  unit price  ext price
0   383081  Isabella  10002  C1-20000         9       43.69     555.83
1   412291    Olivia  10004  A1-06532        56       67.82    2379.36
2   412291    Olivia  10004  A1-82801        31      145.62     686.02
3   412291    Olivia  10004  A1-06532         6       34.55     782.95
4   218896    Sophia  10007  A1-27722        35       67.46    6761.12
5   218896    Sophia  10007  C1-33087        33       26.55     788.65
6   218896    Sophia  10007  C1-33364         8       67.30     676.90
7   218896    Sophia  10007  C1-20000        -1       67.18     -82.18

In [23]:
sales_report=pd.concat([sales_transaction,sales_transaction1], ignore_index=True)
sales_report.sort_values('account')

    account           name  order       sku  quantity  unit price  ext price
5    218895      Kulas Inc  10006  S1-27722        32       95.66    3061.12
6    218895      Kulas Inc  10006  B1-33087        23       22.55     518.65
7    218895      Kulas Inc  10006  B1-20000        -1       72.18     -72.18
12   218896         Sophia  10007  A1-27722        35       67.46    6761.12
13   218896         Sophia  10007  C1-33087        33       26.55     788.65
14   218896         Sophia  10007  C1-33364         8       67.30     676.90
15   218896         Sophia  10007  C1-20000        -1       67.18     -82.18
0    383080       Will LLC  10001  B1-20000         7       33.69     235.83
1    383080       Will LLC  10001  B1-86481         3       35.99     107.97
8    383081       Isabella  10002  C1-20000         9       43.69     555.83
2    412290  Jerde-Hilpert  10005  S1-06532        48       55.82    2679.36
3    412290  Jerde-Hilpert  10005  S1-47412        44       78.91    3472.04
4    412290  Jerde-Hilpert  10005  S1-27722        36       25.42     915.12
9    412291         Olivia  10004  A1-06532        56       67.82    2379.36
10   412291         Olivia  10004  A1-82801        31      145.62     686.02
11   412291         Olivia  10004  A1-06532         6       34.55     782.95

In [27]:
ecommerce_test=pd.merge(ecommerce,ecommerce2, on='Cust_ID', how = 'outer')
ecommerce_test

,Cust_ID,Age,Gender,City,Ord_ID,Ord_quantity,Sales,Ord_priority
0,Cust_1,35.0,Male,Mumbai,Ord_10,4.0,3237.0000,Medium
1,Cust_10,50.0,Male,Pune,NaN,NaN,NaN,NaN
2,Cust_11,NaN,NaN,NaN,Ord_71,1.0,147.6400,Low
3,Cust_2,24.0,Female,Chennai,Ord_14,NaN,NaN,NaN
4,Cust_3,20.0,Female,Delhi,Ord_25,2.0,422.7000,Low
5,Cust_4,45.0,Male,Chennai,Ord_29,15.0,4571.7900,High
6,Cust_5,37.0,Male,Mumbai,Ord_34,8.0,4233.1500,Low
7,Cust_6,40.0,Female,Mumbai,Ord_52,3.0,164.0200,High
8,Cust_8,NaN,NaN,NaN,Ord_94,7.0,3410.1575,Medium

In [29]:
ecommerce_test.isnull().sum()

Cust_ID         0
Age             2
Gender          2
City            2
Ord_ID          1
Ord_quantity    2
Sales           2
Ord_priority    2
dtype: int64