In [1]:
import pandas as pd

mylist=[10,20,30,40,50]
mys=pd.Series(mylist)
print(mys)
print(mys.describe())
#mys

0    10
1    20
2    30
3    40
4    50
dtype: int64
count     5.000000
mean     30.000000
std      15.811388
min      10.000000
25%      20.000000
50%      30.000000
75%      40.000000
max      50.000000
dtype: float64

In [2]:
mys1=pd.Series(mylist, index={0,2,4,6,8})
print(mys1)
mys = pd.Series(mylist, index=["A1", "A2", "A3","A4","A5"])
print(mys)

0    10
2    20
4    30
6    40
8    50
dtype: int64
A1    10
A2    20
A3    30
A4    40
A5    50
dtype: int64

In [28]:
myd={"Empid":101, "Empname":"john", "Salary": 50000}
print(myd)
myw=pd.Series(myd)
mys = pd.Series(list(myd.values()), index=["X", "Y", "Z"])
print(mys)
myf = pd.Series(list(myd.values()), index=["A1", "A2", "A3"])
myf

{'Empid': 101, 'Empname': 'john', 'Salary': 50000}
X      101
Y     john
Z    50000
dtype: object

A1      101
A2     john
A3    50000
dtype: object

In [21]:
mys2=pd.Series(mylist, index=['a','b','c','d','e'])
print(mys2)
print(mys2['b':'e'])

a    10
b    20
c    30
d    40
e    50
dtype: int64
b    20
c    30
d    40
e    50
dtype: int64

In [40]:
s1=pd.Series(range(1,10))
s2=s1[2:]
print(s2)
print(s1>=5)

2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64
0    False
1    False
2    False
3    False
4     True
5     True
6     True
7     True
8     True
dtype: bool

In [3]:
print(pd.__version__)

2.3.3

In [8]:
s1=pd.Series(range(1,10))
print(s1.describe())

count    9.000000
mean     5.000000
std      2.738613
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

In [5]:
s1=pd.Series([1,2,3])
s2=pd.Series([10,20])
print(s1+s2)

0    11.0
1    22.0
2     NaN
dtype: float64

In [12]:
import numpy as np
s=pd.Series([10,np.nan,"John",50.00,None,"Jim",20])
s

0      10
1     NaN
2    John
3    50.0
4    None
5     Jim
6      20
dtype: object

In [64]:
print(s.isnull())
print(s.isnull().sum())
print(s.notnull())
print(s.notnull().sum())
print(s.fillna(0))

0    False
1     True
2    False
3    False
4     True
5    False
6    False
dtype: bool
2
0     True
1    False
2     True
3     True
4    False
5     True
6     True
dtype: bool
5
0      10
1       0
2    John
3    50.0
4       0
5     Jim
6      20
dtype: object

In [65]:
print(s.dropna())
print(s)

0      10
2    John
3    50.0
5     Jim
6      20
dtype: object
0      10
1     NaN
2    John
3    50.0
4    None
5     Jim
6      20
dtype: object

In [29]:
records=[
    {"Name":'Shaun',"Score":140},
    {"Name": "John","Score":100,"City":"Mumbai"}
]
#print(records)
df=pd.DataFrame(records)
#print(df)
df

    Name  Score    City
0  Shaun    140     NaN
1   John    100  Mumbai

In [61]:
#Conversion of different formats in to python data frames 
bm=pd.read_csv(r"C:\Users\suman\OneDrive\Documents\Python Documents\bigmarket.csv")
bm

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [38]:
bm=pd.read_excel(r"C:\Users\suman\OneDrive\Documents\Python Documents\bigmarket.xlsx")
bm

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [79]:
bw=bm.copy()

bw=bw.rename(columns={'Store':'Store_Name','Sales':'Sale'})
bw

    Month Store_Name   Sale
0     Jan          A  31037
1     Jan          B  20722
2     Jan          C  24557
3     Jan          D  34649
4     Jan          E  29795
5     Feb          A  29133
6     Feb          B  22695
7     Feb          C  28312
8     Feb          D  31454
9     Feb          E  46267
10  March          A  32961
11  March          B  26451
12  March          C  47814
13  March          D  36069
14  March          E  31874
15    Apr          A  27253
16    Apr          B  40241
17    Apr          C  47488
18    Apr          D  25432
19    Apr          E  33880
20    May          A  29487
21    May          B  40001
22    May          C  46482
23    May          D  46313
24    May          E  47594

In [78]:
(bm.sample(5))

   Month Store  Sales
18   Apr     D  25432
19   Apr     E  33880
1    Jan     B  20722
16   Apr     B  40241
21   May     B  40001

In [50]:
bm.head(),'\t',bm.tail()

(  Month Store  Sales
 0   Jan     A  31037
 1   Jan     B  20722
 2   Jan     C  24557
 3   Jan     D  34649
 4   Jan     E  29795,
 '\t',
    Month Store  Sales
 20   May     A  29487
 21   May     B  40001
 22   May     C  46482
 23   May     D  46313
 24   May     E  47594)

In [51]:
bm.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Month   25 non-null     object
 1   Store   25 non-null     object
 2   Sales   25 non-null     int64
dtypes: int64(1), object(2)
memory usage: 732.0+ bytes

In [52]:
bm.describe()

             Sales
count     25.00000
mean   34318.44000
std     8604.09835
min    20722.00000
25%    28312.00000
50%    31874.00000
75%    40241.00000
max    47814.00000

In [71]:
bm.shape,bm.columns, bm.dtypes

((25, 3),
 Index(['Month', 'Store', 'Sales'], dtype='object'),
 Month    object
 Store    object
 Sales     int64
 dtype: object)

In [84]:
bw=bw.assign(Grade=np.where(bw['Sale']>40000,'A','B'))
bw

    Month Store_Name   Sale Grade
0     Jan          A  31037     B
1     Jan          B  20722     B
2     Jan          C  24557     B
3     Jan          D  34649     B
4     Jan          E  29795     B
5     Feb          A  29133     B
6     Feb          B  22695     B
7     Feb          C  28312     B
8     Feb          D  31454     B
9     Feb          E  46267     A
10  March          A  32961     B
11  March          B  26451     B
12  March          C  47814     A
13  March          D  36069     B
14  March          E  31874     B
15    Apr          A  27253     B
16    Apr          B  40241     A
17    Apr          C  47488     A
18    Apr          D  25432     B
19    Apr          E  33880     B
20    May          A  29487     B
21    May          B  40001     A
22    May          C  46482     A
23    May          D  46313     A
24    May          E  47594     A