Big Market Data .....
    *The Sample Project is about reading the data from a text file and cleaning the data using pandas and adding the Observations.
    *Added the Profit percentage and profit or loss Column in to the data frame
    *Added the New Observations with the User Inputs.

In [1]:
#Importing the Libraries
import pandas as pd
import numpy as np
#reading the .csv file and getting it into as Python data frames
records=pd.read_csv(r"C:\Users\suman\OneDrive\Documents\Python Documents\bigmarket.txt",sep='\t')
records

    Month Store  Sales
0     Jan     A  31037
1     Jan     B  20722
2     Jan     C  24557
3     Jan     D  34649
4     Jan     E  29795
5     Feb     A  29133
6     Feb     B  22695
7     Feb     C  28312
8     Feb     D  31454
9     Feb     E  46267
10  March     A  32961
11  March     B  26451
12  March     C  47814
13  March     D  36069
14  March     E  31874
15    Apr     A  27253
16    Apr     B  40241
17    Apr     C  47488
18    Apr     D  25432
19    Apr     E  33880
20    May     A  29487
21    May     B  40001
22    May     C  46482
23    May     D  46313
24    May     E  47594

In [34]:
#Duplicating the data (it wont affect the original data)
test=records.copy()
#getting the Information of the dataframe
print(test.info())
test.isnull().sum()
#if missing values is present fill the values with 0
test.fillna(0)
#to drop the Missing Values for temporary
test.dropna()
print("\nThe Overall data(Observations, Variables):",test.shape,"\nVariable Names:",test.columns)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Month   25 non-null     object
 1   Store   25 non-null     object
 2   Sales   25 non-null     int64
dtypes: int64(1), object(2)
memory usage: 732.0+ bytes
None

The Overall data(Observations, Variables): (25, 3)
Variable Names: Index(['Month', 'Store', 'Sales'], dtype='object')

In [24]:
#renaming the Store as Branch 
test=test.rename(columns={'Store':'Branch'})
#Assigning the ProfitorLoss Column..!
test=test.assign(ProfitorLoss=np.where(test['Sales']>35000,'Profit','Loss'))
# Assigning the Profit or loss Percentage Column
test= test.assign(Profit=((test['Sales']*0.10)/test['Sales'])*100)

In [26]:
#Which Month getting profits list...!
print('The Total Profits Count is: ',(test['ProfitorLoss']=='Profit').sum())
test.loc[test['ProfitorLoss'] == 'Profit',['Month','Branch','Sales','ProfitorLoss','Profit']]

The Total Profits Count is:  9

    Month Branch  Sales ProfitorLoss  Profit
9     Feb      E  46267       Profit    10.0
12  March      C  47814       Profit    10.0
13  March      D  36069       Profit    10.0
16    Apr      B  40241       Profit    10.0
17    Apr      C  47488       Profit    10.0
21    May      B  40001       Profit    10.0
22    May      C  46482       Profit    10.0
23    May      D  46313       Profit    10.0
24    May      E  47594       Profit    10.0

In [23]:
#Excluding the Branch A 
print((test['Branch']=='A').sum())
test[~(test['Branch']=='A')]

5

    Month Branch  Sales ProfitorLoss
1     Jan      B  20722         Loss
2     Jan      C  24557         Loss
3     Jan      D  34649         Loss
4     Jan      E  29795         Loss
6     Feb      B  22695         Loss
7     Feb      C  28312         Loss
8     Feb      D  31454         Loss
9     Feb      E  46267       Profit
11  March      B  26451         Loss
12  March      C  47814       Profit
13  March      D  36069       Profit
14  March      E  31874         Loss
16    Apr      B  40241       Profit
17    Apr      C  47488       Profit
18    Apr      D  25432         Loss
19    Apr      E  33880         Loss
21    May      B  40001       Profit
22    May      C  46482       Profit
23    May      D  46313       Profit
24    May      E  47594       Profit

In [28]:
#Query based conditions
test.query("Month in ['Jan','Feb'] and ProfitorLoss == 'Profit'")
test.query("Branch in ['A','C','D','E'] and Sales > 30000 and ProfitorLoss == 'Profit'")

    Month Branch  Sales ProfitorLoss  Profit
9     Feb      E  46267       Profit    10.0
12  March      C  47814       Profit    10.0
13  March      D  36069       Profit    10.0
17    Apr      C  47488       Profit    10.0
22    May      C  46482       Profit    10.0
23    May      D  46313       Profit    10.0
24    May      E  47594       Profit    10.0

In [30]:
#Before Adding the Observations the information of the Data Frame...!
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Month         25 non-null     object
 1   Branch        25 non-null     object
 2   Sales         25 non-null     int64
 3   ProfitorLoss  25 non-null     object
 4   Profit        25 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.1+ KB

In [31]:
#Creating the New Observations with User Inputs...!
a=input('Enter the Month:')
b=input('Enter the Branch:')
c=int(input('Enter the Sale:'))
new_data = {
    'Month': a,
    'Branch': b,
    'Sales': c ,
    'ProfitorLoss': np.where(c>35000,'Profit','Loss'),
    'Profit': ((c*0.10)/c)*100
}
new_row=pd.DataFrame([new_data])
test=pd.concat([test,new_row], ignore_index=True)
test.tail()

Enter the Month: Sep
Enter the Branch: F
Enter the Sale: 15478

   Month Branch  Sales ProfitorLoss  Profit
21   May      B  40001       Profit    10.0
22   May      C  46482       Profit    10.0
23   May      D  46313       Profit    10.0
24   May      E  47594       Profit    10.0
25   Sep      F  15478         Loss    10.0

In [32]:
#After adding the New Observations The Information ...
test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Month         26 non-null     object
 1   Branch        26 non-null     object
 2   Sales         26 non-null     int64
 3   ProfitorLoss  26 non-null     object
 4   Profit        26 non-null     float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.1+ KB